# Generated by Django 4.1.3 on 2022-11-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images')),
                ('action', models.CharField(choices=[('COLOR_BGR2GRAY', 'color_bgr2gray'), ('COLOR_BGR2HSV', 'color_bgr2hsv'), ('COLOR_BGR2LAB', 'color_bgr2lab')], max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
